name: Tests
on:
  push:
    branches:
      - main
  pull_request:


jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
          node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Run tests
      run: npm run tests