name: Update Database
on:
  push:

jobs:
  update-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run TS-Skript
        run: npx ts-node --compiler-options '{"module":"CommonJS"}' generateIconDB.ts
        working-directory: database/icons